# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: emailservice
      context: src/emailservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/productcatalogservice
      context: src/productcatalogservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/recommendationservice
      context: src/recommendationservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/shoppingassistantservice
      context: src/shoppingassistantservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/shippingservice
      context: src/shippingservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/checkoutservice
      context: src/checkoutservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/paymentservice
      context: src/paymentservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/currencyservice
      context: src/currencyservice
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/cartservice
      context: src/cartservice/src
      docker:
        dockerfile: Dockerfile
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/frontend
      context: src/frontend
    - image: aus-docker.pkg.dev/boutique-ms-demo/pr-images/dservice
      context: src/adservice
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
manifests:
  kustomize:
    paths:
      - kubernetes-manifests
deploy:
  kubectl: {}
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        diskSizeGb: 300
        machineType: N1_HIGHCPU_32
        timeout: 4000s
  - name: debug
    activation:
      - command: debug
    patches:
      - op: replace
        path: /build/artifacts/8/docker/dockerfile
        value: Dockerfile.debug
  - name: network-policies
    patches:
      - op: add
        path: /manifests/kustomize/paths/1
        value: kustomize/components/network-policies
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: loadgenerator
requires:
  - configs:
      - app
build:
  artifacts:
    - image: us-docker.pkg.dev/boutique-ms-demo/pr-images/loadgenerator
      context: src/loadgenerator
manifests:
  rawYaml:
    - ./kubernetes-manifests/loadgenerator.yaml
deploy:
  kubectl: {}
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        diskSizeGb: 300
        machineType: N1_HIGHCPU_32
        timeout: 4000s
