# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.




name: "Continuous Integration - Pull Request"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
      - 'terraform/**'
      - '.github/workflows/terraform-validate-ci.yaml'
      - 'helm-chart/**'
      - '.github/workflows/helm-chart-ci.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deployment-tests:
    runs-on: [self-hosted, is-enabled]
    env:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      PR_CLUSTER: ${{ secrets.PR_CLUSTER }}
      REGION: ${{ secrets.REGION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug key.json
        run: |
          cat key.json

      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $PROJECT_ID

      - name: Connect to GKE Cluster
        run: |
          gcloud container clusters get-credentials $PR_CLUSTER --region $REGION

      - name: Create Namespace for PR
        run: |
          NAMESPACE="pr${{ github.event.pull_request.number }}"
          kubectl create namespace $NAMESPACE || echo "Namespace already exists"

      - name: Build and Push Images with Skaffold
        run: |
          NAMESPACE="pr${{ github.event.pull_request.number }}"
          skaffold config set --global local-cluster false
          skaffold run --default-repo=us-docker.pkg.dev/$PROJECT_ID/refs/pull/${{ github.event.pull_request.number }} \
            --tag=${{ github.event.pull_request.number }} \
            --namespace=$NAMESPACE -p network-policies

      - name: Wait for Pods to be Ready
        run: |
          NAMESPACE="pr${{ github.event.pull_request.number }}"
          kubectl -n $NAMESPACE wait --for=condition=available --timeout=1000s deployment --all

      - name: Query External IP for Frontend Service
        run: |
          NAMESPACE="pr${{ github.event.pull_request.number }}"
          kubectl -n $NAMESPACE get service frontend-external -o jsonpath='{.status.loadBalancer.ingress[0].ip}'

      - name: Clean Up Namespace (Optional)
        if: ${{ always() }}
        run: |
          NAMESPACE="pr${{ github.event.pull_request.number }}"
          kubectl delete namespace $NAMESPACE || echo "Namespace already deleted"
